import { Asset } from './table.module';

export const assets: Asset[] = [
  {
    AssetId: 'A001',
    Description: 'Web Server',
    VM_Location: 'us-central1-a',
    SAP_Room: 'Room 101',
    Status: 'Active',
    Action: 'Monitor',
  },
  {
    AssetId: 'A002',
    Description: 'Database Server',
    VM_Location: 'us-central1-b',
    SAP_Room: 'Room 102',
    Status: 'Inactive',
    Action: 'Start',
  },
  {
    AssetId: 'A003',
    Description: 'Application Server',
    VM_Location: 'europe-west1-c',
    SAP_Room: 'Room 201',
    Status: 'Maintenance',
    Action: 'Update',
  },
  {
    AssetId: 'A004',
    Description: 'Backup Server',
    VM_Location: 'asia-east1-a',
    SAP_Room: 'Room 202',
    Status: 'Active',
    Action: 'Backup',
  },
  {
    AssetId: 'A005',
    Description: 'Testing Server',
    VM_Location: 'us-east1-d',
    SAP_Room: 'Room 103',
    Status: 'Active',
    Action: 'Test',
  },
  {
    AssetId: 'A006',
    Description: 'File Server',
    VM_Location: 'us-west1-a',
    SAP_Room: 'Room 104',
    Status: 'Active',
    Action: 'Sync',
  },
  {
    AssetId: 'A007',
    Description: 'Email Server',
    VM_Location: 'europe-north1-b',
    SAP_Room: 'Room 105',
    Status: 'Active',
    Action: 'Send',
  },
  {
    AssetId: 'A008',
    Description: 'DNS Server',
    VM_Location: 'asia-southeast1-c',
    SAP_Room: 'Room 106',
    Status: 'Inactive',
    Action: 'Restart',
  },
  {
    AssetId: 'A009',
    Description: 'Proxy Server',
    VM_Location: 'us-central1-c',
    SAP_Room: 'Room 107',
    Status: 'Active',
    Action: 'Monitor',
  },
  {
    AssetId: 'A010',
    Description: 'Authentication Server',
    VM_Location: 'europe-west2-a',
    SAP_Room: 'Room 108',
    Status: 'Active',
    Action: 'Authenticate',
  },
  {
    AssetId: 'A011',
    Description: 'Development Server',
    VM_Location: 'us-east1-a',
    SAP_Room: 'Room 109',
    Status: 'Active',
    Action: 'Deploy',
  },
  {
    AssetId: 'A012',
    Description: 'Staging Server',
    VM_Location: 'us-west1-b',
    SAP_Room: 'Room 110',
    Status: 'Maintenance',
    Action: 'Prepare',
  },
  {
    AssetId: 'A013',
    Description: 'Production Server',
    VM_Location: 'asia-east2-a',
    SAP_Room: 'Room 111',
    Status: 'Active',
    Action: 'Run',
  },
  {
    AssetId: 'A014',
    Description: 'Load Balancer',
    VM_Location: 'europe-west1-b',
    SAP_Room: 'Room 112',
    Status: 'Active',
    Action: 'Balance',
  },
  {
    AssetId: 'A015',
    Description: 'Cache Server',
    VM_Location: 'us-central1-d',
    SAP_Room: 'Room 113',
    Status: 'Inactive',
    Action: 'Clear',
  },
  {
    AssetId: 'A016',
    Description: 'CI/CD Server',
    VM_Location: 'asia-northeast1-c',
    SAP_Room: 'Room 114',
    Status: 'Active',
    Action: 'Build',
  },
  {
    AssetId: 'A017',
    Description: 'Analytics Server',
    VM_Location: 'europe-west3-a',
    SAP_Room: 'Room 115',
    Status: 'Active',
    Action: 'Analyze',
  },
  {
    AssetId: 'A018',
    Description: 'Log Server',
    VM_Location: 'us-east1-c',
    SAP_Room: 'Room 116',
    Status: 'Active',
    Action: 'Collect',
  },
  {
    AssetId: 'A019',
    Description: 'Security Server',
    VM_Location: 'asia-southeast1-b',
    SAP_Room: 'Room 117',
    Status: 'Active',
    Action: 'Scan',
  },
  {
    AssetId: 'A020',
    Description: 'API Gateway',
    VM_Location: 'europe-west4-b',
    SAP_Room: 'Room 118',
    Status: 'Active',
    Action: 'Route',
  },
  {
    AssetId: 'A021',
    Description: 'Monitoring Server',
    VM_Location: 'us-central1-a',
    SAP_Room: 'Room 119',
    Status: 'Active',
    Action: 'Monitor',
  },
  {
    AssetId: 'A022',
    Description: 'Notification Server',
    VM_Location: 'asia-east1-b',
    SAP_Room: 'Room 120',
    Status: 'Active',
    Action: 'Notify',
  },
  {
    AssetId: 'A023',
    Description: 'Task Scheduler',
    VM_Location: 'europe-west1-d',
    SAP_Room: 'Room 121',
    Status: 'Active',
    Action: 'Schedule',
  },
  {
    AssetId: 'A024',
    Description: 'Message Queue Server',
    VM_Location: 'us-central1-b',
    SAP_Room: 'Room 122',
    Status: 'Inactive',
    Action: 'Start',
  },
  {
    AssetId: 'A025',
    Description: 'ML Training Server',
    VM_Location: 'asia-south1-c',
    SAP_Room: 'Room 123',
    Status: 'Active',
    Action: 'Train',
  },
];
